/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedProfessorRouteImport } from './routes/_authenticated/professor'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMeuTreinoRouteImport } from './routes/_authenticated/meu-treino'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFichaIdRouteImport } from './routes/_authenticated/ficha.$id'
import { Route as AuthenticatedFichaIdHistoricoRouteImport } from './routes/_authenticated/ficha.$id.historico'
import { Route as AuthenticatedFichaIdExecutarRouteImport } from './routes/_authenticated/ficha.$id.executar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessorRoute = AuthenticatedProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuTreinoRoute = AuthenticatedMeuTreinoRouteImport.update({
  id: '/meu-treino',
  path: '/meu-treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichaIdRoute = AuthenticatedFichaIdRouteImport.update({
  id: '/ficha/$id',
  path: '/ficha/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichaIdHistoricoRoute =
  AuthenticatedFichaIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedFichaIdRoute,
  } as any)
const AuthenticatedFichaIdExecutarRoute =
  AuthenticatedFichaIdExecutarRouteImport.update({
    id: '/executar',
    path: '/executar',
    getParentRoute: () => AuthenticatedFichaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professor': typeof AuthenticatedProfessorRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ficha/$id': typeof AuthenticatedFichaIdRouteWithChildren
  '/ficha/$id/executar': typeof AuthenticatedFichaIdExecutarRoute
  '/ficha/$id/historico': typeof AuthenticatedFichaIdHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professor': typeof AuthenticatedProfessorRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ficha/$id': typeof AuthenticatedFichaIdRouteWithChildren
  '/ficha/$id/executar': typeof AuthenticatedFichaIdExecutarRoute
  '/ficha/$id/historico': typeof AuthenticatedFichaIdHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/professor': typeof AuthenticatedProfessorRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/ficha/$id': typeof AuthenticatedFichaIdRouteWithChildren
  '/_authenticated/ficha/$id/executar': typeof AuthenticatedFichaIdExecutarRoute
  '/_authenticated/ficha/$id/historico': typeof AuthenticatedFichaIdHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/app'
    | '/configuracoes'
    | '/mensagens'
    | '/meu-treino'
    | '/perfil'
    | '/professor'
    | '/progresso'
    | '/ficha/$id'
    | '/ficha/$id/executar'
    | '/ficha/$id/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/app'
    | '/configuracoes'
    | '/mensagens'
    | '/meu-treino'
    | '/perfil'
    | '/professor'
    | '/progresso'
    | '/ficha/$id'
    | '/ficha/$id/executar'
    | '/ficha/$id/historico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/app'
    | '/_authenticated/configuracoes'
    | '/_authenticated/mensagens'
    | '/_authenticated/meu-treino'
    | '/_authenticated/perfil'
    | '/_authenticated/professor'
    | '/_authenticated/progresso'
    | '/_authenticated/ficha/$id'
    | '/_authenticated/ficha/$id/executar'
    | '/_authenticated/ficha/$id/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professor': {
      id: '/_authenticated/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof AuthenticatedProfessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-treino': {
      id: '/_authenticated/meu-treino'
      path: '/meu-treino'
      fullPath: '/meu-treino'
      preLoaderRoute: typeof AuthenticatedMeuTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ficha/$id': {
      id: '/_authenticated/ficha/$id'
      path: '/ficha/$id'
      fullPath: '/ficha/$id'
      preLoaderRoute: typeof AuthenticatedFichaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ficha/$id/historico': {
      id: '/_authenticated/ficha/$id/historico'
      path: '/historico'
      fullPath: '/ficha/$id/historico'
      preLoaderRoute: typeof AuthenticatedFichaIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedFichaIdRoute
    }
    '/_authenticated/ficha/$id/executar': {
      id: '/_authenticated/ficha/$id/executar'
      path: '/executar'
      fullPath: '/ficha/$id/executar'
      preLoaderRoute: typeof AuthenticatedFichaIdExecutarRouteImport
      parentRoute: typeof AuthenticatedFichaIdRoute
    }
  }
}

interface AuthenticatedFichaIdRouteChildren {
  AuthenticatedFichaIdExecutarRoute: typeof AuthenticatedFichaIdExecutarRoute
  AuthenticatedFichaIdHistoricoRoute: typeof AuthenticatedFichaIdHistoricoRoute
}

const AuthenticatedFichaIdRouteChildren: AuthenticatedFichaIdRouteChildren = {
  AuthenticatedFichaIdExecutarRoute: AuthenticatedFichaIdExecutarRoute,
  AuthenticatedFichaIdHistoricoRoute: AuthenticatedFichaIdHistoricoRoute,
}

const AuthenticatedFichaIdRouteWithChildren =
  AuthenticatedFichaIdRoute._addFileChildren(AuthenticatedFichaIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMeuTreinoRoute: typeof AuthenticatedMeuTreinoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProfessorRoute: typeof AuthenticatedProfessorRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedFichaIdRoute: typeof AuthenticatedFichaIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMeuTreinoRoute: AuthenticatedMeuTreinoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProfessorRoute: AuthenticatedProfessorRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedFichaIdRoute: AuthenticatedFichaIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
